name: React CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  react_build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd client && yarn install

      - name: Build React App
        run: cd client && yarn build

  docker_build_push:
    needs: [react_build]
    runs-on: ubuntu-20.04
    steps:
      - name: docker login
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build --file ./client/Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/vending-machine:$(date +%s) .

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USERNAME}}/vending-machine