name: vending-machine CD tests
on:
  push:
    branches:
      - dev

jobs:
  docker_build_push:
    runs-on: ubuntu-20.04
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Push
        run: |
          VERSION=$(date +%s)
          cd client
          docker build --tag ${{secrets.DOCKER_USERNAME}}/vending-machine:${VERSION} .
          docker login -u ${{DOCKER_USERNAME}} -p ${{DOCKER_PASSWORD}}
          docker push ${{secrets.DOCKER_USERNAME}}/vending-machine:${VERSION}